namespace ProcInsider.Features.WindowsSecurityDetails;

// Observed layouts only. Sanitized fixtures and provenance are retained in CaptureWorkspaceSelfTest.
public static class SecurityDetailsDefaults
{
    public static SecurityDetailsDefinition[] All =>
    [
        new(4624, @"user:$TargetDomainName$\$TargetUserName$; SRC:$IpAddress$; workstation:$WorkstationName$; logon type:$LogonType$", [new(3, ["SubjectUserSid", "SubjectUserName", "SubjectDomainName", "SubjectLogonId", "TargetUserSid", "TargetUserName", "TargetDomainName", "TargetLogonId", "LogonType", "LogonProcessName", "AuthenticationPackageName", "WorkstationName", "LogonGuid", "TransmittedServices", "LmPackageName", "KeyLength", "ProcessId", "ProcessName", "IpAddress", "IpPort", "ImpersonationLevel", "RestrictedAdminMode", "RemoteCredentialGuard", "TargetOutboundUserName", "TargetOutboundDomainName", "VirtualAccount", "TargetLinkedLogonId", "ElevatedToken"])]),
        new(4657, @"registry:$ObjectName$; value:$ObjectValueName$; operation:$OperationType$", [new(0, ["SubjectUserSid", "SubjectUserName", "SubjectDomainName", "SubjectLogonId", "ObjectName", "ObjectValueName", "HandleId", "OperationType", "OldValueType", "OldValue", "NewValueType", "NewValue", "ProcessId", "ProcessName"])]),
        new(4659, @"delete-intent handle request:$ObjectName$; access:$AccessMask$", [new(0, ["SubjectUserSid", "SubjectUserName", "SubjectDomainName", "SubjectLogonId", "ObjectServer", "ObjectType", "ObjectName", "HandleId", "TransactionId", "AccessList", "AccessMask", "PrivilegeList", "ProcessId"])]),
        new(4663, @"object:$ObjectName$; access used:$AccessMask$", [new(1, ["SubjectUserSid", "SubjectUserName", "SubjectDomainName", "SubjectLogonId", "ObjectServer", "ObjectType", "ObjectName", "HandleId", "AccessList", "AccessMask", "ProcessId", "ProcessName", "ResourceAttributes"])]),
        new(4670, @"permissions changed:$ObjectName$; actor:$SubjectDomainName$\$SubjectUserName$", [new(0, ["SubjectUserSid", "SubjectUserName", "SubjectDomainName", "SubjectLogonId", "ObjectServer", "ObjectType", "ObjectName", "HandleId", "OldSd", "NewSd", "ProcessId", "ProcessName"])]),
        new(4673, @"privileged service call:$Service$; privileges:$PrivilegeList$", [new(0, ["SubjectUserSid", "SubjectUserName", "SubjectDomainName", "SubjectLogonId", "ObjectServer", "Service", "PrivilegeList", "ProcessId", "ProcessName"])]),
        new(4674, @"privileged object operation:$ObjectName$; privileges:$PrivilegeList$", [new(0, ["SubjectUserSid", "SubjectUserName", "SubjectDomainName", "SubjectLogonId", "ObjectServer", "ObjectType", "ObjectName", "HandleId", "AccessMask", "PrivilegeList", "ProcessId", "ProcessName"])]),
        new(4688, @"image:$NewProcessName$; parent:$ParentProcessName$; cmd:$CommandLine$", [new(2, ["SubjectUserSid", "SubjectUserName", "SubjectDomainName", "SubjectLogonId", "NewProcessId", "NewProcessName", "TokenElevationType", "ProcessId", "CommandLine", "TargetUserSid", "TargetUserName", "TargetDomainName", "TargetLogonId", "ParentProcessName", "MandatoryLabel"])]),
        new(4689, @"image:$ProcessName$; exit status:$Status$", [new(0, ["SubjectUserSid", "SubjectUserName", "SubjectDomainName", "SubjectLogonId", "Status", "ProcessId", "ProcessName"])]),
        new(4703, @"target:$TargetDomainName$\$TargetUserName$; enabled:$EnabledPrivilegeList$; disabled:$DisabledPrivilegeList$", [new(0, ["SubjectUserSid", "SubjectUserName", "SubjectDomainName", "SubjectLogonId", "TargetUserSid", "TargetUserName", "TargetDomainName", "TargetLogonId", "ProcessName", "ProcessId", "EnabledPrivilegeList", "DisabledPrivilegeList"])]),
        new(4798, @"membership queried:$TargetDomainName$\$TargetUserName$; caller:$CallerProcessName$", [new(0, ["TargetUserName", "TargetDomainName", "TargetSid", "SubjectUserSid", "SubjectUserName", "SubjectDomainName", "SubjectLogonId", "CallerProcessId", "CallerProcessName"])]),
        new(4907, @"auditing settings changed:$ObjectName$; actor:$SubjectDomainName$\$SubjectUserName$", [new(0, ["SubjectUserSid", "SubjectUserName", "SubjectDomainName", "SubjectLogonId", "ObjectServer", "ObjectType", "ObjectName", "HandleId", "OldSd", "NewSd", "ProcessId", "ProcessName"])]),
        new(5156, @"WFP allowed; SRC:[$SourceAddress$]:$SourcePort$; DST:[$DestAddress$]:$DestPort$; protocol:$Protocol$", [new(1, ["ProcessID", "Application", "Direction", "SourceAddress", "SourcePort", "DestAddress", "DestPort", "Protocol", "InterfaceIndex", "FilterOrigin", "FilterRTID", "LayerName", "LayerRTID", "RemoteUserID", "RemoteMachineID"])]),
        new(5157, @"WFP blocked; SRC:[$SourceAddress$]:$SourcePort$; DST:[$DestAddress$]:$DestPort$; protocol:$Protocol$", [new(3, ["ProcessID", "Application", "Direction", "SourceAddress", "SourcePort", "DestAddress", "DestPort", "Protocol", "InterfaceIndex", "FilterOrigin", "FilterRTID", "LayerName", "LayerRTID", "RemoteUserID", "RemoteMachineID", "OriginalProfile", "CurrentProfile", "IsLoopback", "HasRemoteDynamicKeywordAddress"])]),
        new(5158, @"WFP bind allowed; local:[$SourceAddress$]:$SourcePort$; protocol:$Protocol$", [new(0, ["ProcessId", "Application", "SourceAddress", "SourcePort", "Protocol", "FilterRTID", "LayerName", "LayerRTID"])]),
    ];
}
